const calculateInitialStock = (variants) => {
  if (!variants || variants.length === 0) return 0;

  return variants.reduce((total, variant) => total + variant.stock, 0);
};

export const productDataList = [
  {
    id: 1,
    name: "Giày thể thao CA Match",
    categoryId: "C001",
    price: 2300000,
    oldPrice: 2400000,
    img: "./img/giaythethao_CAMatch.avif",
    rating: 5,
    ratingCount: 128,
    badge: "hot",
    description:
      "Giày thể thao CA Match với thiết kế hiện đại, đế cao su bền bỉ, chất liệu thoáng khí, phù hợp cho các hoạt động thể thao và dạo phố.",
    images: [
      "./img/giaythethao_CAMatch.avif",
      "./img/giaythethao_CAMatch.avif",
      "./img/giaythethao_CAMatch.avif",
    ],

    variants: [
      { size: 38, stock: 10 },
      { size: 39, stock: 12 },
      { size: 40, stock: 15 },
      { size: 41, stock: 18 },
      { size: 42, stock: 12 },
      { size: 43, stock: 8 },
    ],

    costPrice: 1650000,
    initialStock: calculateInitialStock([
      { size: 38, stock: 10 },
      { size: 39, stock: 12 },
      { size: 40, stock: 15 },
      { size: 41, stock: 18 },
      { size: 42, stock: 12 },
      { size: 43, stock: 8 },
    ]),
    lowStockThreshold: 5,
    imports: [],
    sales: [],
    isHidden: false,
  },
  {
    id: 2,
    name: "Giày thể thao Suede Classic Unisex",
    categoryId: "C001",
    price: 1840000,
    oldPrice: 2300000,
    img: "./img/Giày-thể-thao-Suede-Classic-Unisex.avif",
    rating: 4,
    ratingCount: 95,
    badge: "sale",
    description:
      "Mẫu giày Suede Classic mang phong cách retro, chất liệu da lộn cao cấp, dễ phối đồ, phù hợp cho cả nam và nữ.",
    images: [
      "./img/Giày-thể-thao-Suede-Classic-Unisex.avif",
      "./img/Giày-thể-thao-Suede-Classic-Unisex.avif",
    ],

    variants: [
      { size: 36, stock: 8 },
      { size: 37, stock: 10 },
      { size: 38, stock: 12 },
      { size: 39, stock: 15 },
      { size: 40, stock: 18 },
      { size: 41, stock: 14 },
    ],

    costPrice: 1250000,
    initialStock: calculateInitialStock([
      { size: 36, stock: 8 },
      { size: 37, stock: 10 },
      { size: 38, stock: 12 },
      { size: 39, stock: 15 },
      { size: 40, stock: 18 },
      { size: 41, stock: 14 },
    ]),
    lowStockThreshold: 6,
    imports: [],
    sales: [],
    isHidden: false,
  },
  {
    id: 3,
    name: "GIÀY DA CÔNG SỞ (DA THẬT) - GERMANO BELLESI - SẢN XUẤT THỦ CÔNG TẠI ITALY",
    categoryId: "C002",
    price: 10990000,
    oldPrice: null,
    img: "./img/giaycongsoGERMANO.webp",
    rating: 5,
    ratingCount: 203,
    badge: "new",
    description:
      "Giày da công sở Germano Bellesi được sản xuất thủ công tại Ý, sử dụng da thật cao cấp, mang lại sự sang trọng và đẳng cấp cho phái mạnh.",
    images: ["./img/giaycongsoGERMANO.webp", "./img/giaycongsoGERMANO.webp"],

    variants: [
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ],

    costPrice: 8200000,
    initialStock: 8,
    lowStockThreshold: 3,
    imports: [
      {
        date: "2025-09-15T00:00:00Z",
        qty: 5,
        costPrice: 8200000,
        note: "Nhập đợt 1",
      },
      {
        date: "2025-10-01T00:00:00Z",
        qty: 3,
        costPrice: 8200000,
        note: "Nhập bổ sung",
      },
    ],
    sales: [],
    isHidden: false,
  },
  {
    id: 4,
    name: "Giày Boots nam MATURE Chelsea Boots – Đen – Version 2025",
    categoryId: "C002",
    price: 1399000,
    oldPrice: null,
    img: "./img/bootsnam.webp",
    rating: 4,
    ratingCount: 76,
    badge: null,
    description:
      "Chelsea Boots MATURE phiên bản 2025 với thiết kế tối giản, chất liệu da bền đẹp, dễ phối đồ, phù hợp cho phong cách lịch lãm và cá tính.",
    images: ["./img/bootsnam.webp", "./img/bootsnam.webp"],

    variants: [
      { size: 39, stock: 6 },
      { size: 40, stock: 10 },
      { size: 41, stock: 12 },
      { size: 42, stock: 8 },
      { size: 43, stock: 5 },
    ],

    costPrice: 980000,
    initialStock: calculateInitialStock([
      { size: 39, stock: 6 },
      { size: 40, stock: 10 },
      { size: 41, stock: 12 },
      { size: 42, stock: 8 },
      { size: 43, stock: 5 },
    ]),
    lowStockThreshold: 4,
    imports: [],
    sales: [],
    isHidden: false,
  },
  {
    id: 5,
    name: "Giày Sneaker nam DYNAMIC – Vàng bò – Version 2025",
    categoryId: "C001",
    price: 1399000,
    oldPrice: null,
    img: "./img/casual_Dynamic.webp",
    rating: 5,
    ratingCount: 156,
    badge: null,
    description:
      "Sneaker DYNAMIC phiên bản 2025 với màu vàng bò nổi bật, thiết kế trẻ trung, đế êm ái, mang lại sự thoải mái cho cả ngày dài.",
    images: ["./img/casual_Dynamic.webp", "./img/casual_Dynamic.webp"],

    variants: [
      { size: 38, stock: 8 },
      { size: 39, stock: 15 },
      { size: 40, stock: 18 },
      { size: 41, stock: 15 },
      { size: 42, stock: 10 },
    ],

    costPrice: 960000,
    initialStock: calculateInitialStock([
      { size: 38, stock: 8 },
      { size: 39, stock: 15 },
      { size: 40, stock: 18 },
      { size: 41, stock: 15 },
      { size: 42, stock: 10 },
    ]),
    lowStockThreshold: 6,
    imports: [],
    sales: [],
    isHidden: false,
  },
  {
    id: 6,
    name: "Giày nam Warrior 2025 phong cách trẻ trung",
    categoryId: "C001",
    price: 522500,
    oldPrice: 550000,
    img: "./img/casual_Warrior.png",
    rating: 4,
    ratingCount: 89,
    badge: "sale",
    description:
      "Giày Warrior 2025 với phong cách trẻ trung, giá cả hợp lý, chất liệu nhẹ và bền, phù hợp cho sinh viên và giới trẻ năng động.",
    images: ["./img/casual_Warrior.png", "./img/casual_Warrior.png"],

    variants: [
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ],

    costPrice: 370000,
    initialStock: calculateInitialStock([
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ]),
    lowStockThreshold: 8,
    imports: [],
    sales: [],
    isHidden: false,
  },
  {
    id: 7,
    name: "Giày nam Warrior 2025 phong cách trẻ trung",
    categoryId: "C001",
    price: 522500,
    oldPrice: 550000,
    img: "./img/casual_Warrior.png",
    rating: 4,
    ratingCount: 89,
    badge: "sale",
    description:
      "Giày Warrior 2025 với phong cách trẻ trung, giá cả hợp lý, chất liệu nhẹ và bền, phù hợp cho sinh viên và giới trẻ năng động.",
    images: ["./img/casual_Warrior.png", "./img/casual_Warrior.png"],

    variants: [
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ],

    costPrice: 370000,
    initialStock: calculateInitialStock([
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ]),
    lowStockThreshold: 8,
    imports: [],
    sales: [],
    isHidden: false,
  },
  {
    id: 8,
    name: "Giày nam Warrior 2025 phong cách trẻ trung",
    categoryId: "C001",
    price: 522500,
    oldPrice: 550000,
    img: "./img/casual_Warrior.png",
    rating: 4,
    ratingCount: 89,
    badge: "sale",
    description:
      "Giày Warrior 2025 với phong cách trẻ trung, giá cả hợp lý, chất liệu nhẹ và bền, phù hợp cho sinh viên và giới trẻ năng động.",
    images: ["./img/casual_Warrior.png", "./img/casual_Warrior.png"],

    variants: [
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ],

    costPrice: 370000,
    initialStock: calculateInitialStock([
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ]),
    lowStockThreshold: 8,
    imports: [],
    sales: [],
    isHidden: false,
  },
  {
    id: 9,
    name: "Giày nam Warrior 2025 phong cách trẻ trung",
    categoryId: "C001",
    price: 522500,
    oldPrice: 550000,
    img: "./img/casual_Warrior.png",
    rating: 4,
    ratingCount: 89,
    badge: "sale",
    description:
      "Giày Warrior 2025 với phong cách trẻ trung, giá cả hợp lý, chất liệu nhẹ và bền, phù hợp cho sinh viên và giới trẻ năng động.",
    images: ["./img/casual_Warrior.png", "./img/casual_Warrior.png"],

    variants: [
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ],

    costPrice: 370000,
    initialStock: calculateInitialStock([
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ]),
    lowStockThreshold: 8,
    imports: [],
    sales: [],
    isHidden: false,
  },
  {
    id: 10,
    name: "Giày nam Warrior 2025 phong cách trẻ trung",
    categoryId: "C001",
    price: 522500,
    oldPrice: 550000,
    img: "./img/casual_Warrior.png",
    rating: 4,
    ratingCount: 89,
    badge: "sale",
    description:
      "Giày Warrior 2025 với phong cách trẻ trung, giá cả hợp lý, chất liệu nhẹ và bền, phù hợp cho sinh viên và giới trẻ năng động.",
    images: ["./img/casual_Warrior.png", "./img/casual_Warrior.png"],

    variants: [
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ],

    costPrice: 370000,
    initialStock: calculateInitialStock([
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ]),
    lowStockThreshold: 8,
    imports: [],
    sales: [],
    isHidden: false,
  },
  {
    id: 11,
    name: "Giày nam Warrior 2025 phong cách trẻ trung",
    categoryId: "C001",
    price: 522500,
    oldPrice: 550000,
    img: "./img/casual_Warrior.png",
    rating: 4,
    ratingCount: 89,
    badge: "sale",
    description:
      "Giày Warrior 2025 với phong cách trẻ trung, giá cả hợp lý, chất liệu nhẹ và bền, phù hợp cho sinh viên và giới trẻ năng động.",
    images: ["./img/casual_Warrior.png", "./img/casual_Warrior.png"],

    variants: [
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ],

    costPrice: 370000,
    initialStock: calculateInitialStock([
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ]),
    lowStockThreshold: 8,
    imports: [],
    sales: [],
    isHidden: false,
  },
  {
    id: 12,
    name: "Giày nam Warrior 2025 phong cách trẻ trung",
    categoryId: "C001",
    price: 522500,
    oldPrice: 550000,
    img: "./img/casual_Warrior.png",
    rating: 4,
    ratingCount: 89,
    badge: "sale",
    description:
      "Giày Warrior 2025 với phong cách trẻ trung, giá cả hợp lý, chất liệu nhẹ và bền, phù hợp cho sinh viên và giới trẻ năng động.",
    images: ["./img/casual_Warrior.png", "./img/casual_Warrior.png"],

    variants: [
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ],

    costPrice: 370000,
    initialStock: calculateInitialStock([
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ]),
    lowStockThreshold: 8,
    imports: [],
    sales: [],
    isHidden: false,
  },
  {
    id: 13,
    name: "Giày nam Warrior 2025 phong cách trẻ trung",
    categoryId: "C001",
    price: 522500,
    oldPrice: 550000,
    img: "./img/casual_Warrior.png",
    rating: 4,
    ratingCount: 89,
    badge: "sale",
    description:
      "Giày Warrior 2025 với phong cách trẻ trung, giá cả hợp lý, chất liệu nhẹ và bền, phù hợp cho sinh viên và giới trẻ năng động.",
    images: ["./img/casual_Warrior.png", "./img/casual_Warrior.png"],

    variants: [
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ],

    costPrice: 370000,
    initialStock: calculateInitialStock([
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ]),
    lowStockThreshold: 8,
    imports: [],
    sales: [],
    isHidden: false,
  },
  {
    id: 14,
    name: "Giày nam Warrior 2025 phong cách trẻ trung",
    categoryId: "C001",
    price: 522500,
    oldPrice: 550000,
    img: "./img/casual_Warrior.png",
    rating: 4,
    ratingCount: 89,
    badge: "sale",
    description:
      "Giày Warrior 2025 với phong cách trẻ trung, giá cả hợp lý, chất liệu nhẹ và bền, phù hợp cho sinh viên và giới trẻ năng động.",
    images: ["./img/casual_Warrior.png", "./img/casual_Warrior.png"],
    variants: [
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ],
    costPrice: 370000,
    initialStock: calculateInitialStock([
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ]),
    lowStockThreshold: 8,
    imports: [],
    sales: [],
    isHidden: false,
  },
  {
    id: 15,
    name: "Giày nam Warrior 2025 phong cách trẻ trung",
    categoryId: "C001",
    price: 522500,
    oldPrice: 550000,
    img: "./img/casual_Warrior.png",
    rating: 4,
    ratingCount: 89,
    badge: "sale",
    description:
      "Giày Warrior 2025 với phong cách trẻ trung, giá cả hợp lý, chất liệu nhẹ và bền, phù hợp cho sinh viên và giới trẻ năng động.",
    images: ["./img/casual_Warrior.png", "./img/casual_Warrior.png"],
    variants: [
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ],
    costPrice: 370000,
    initialStock: calculateInitialStock([
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ]),
    lowStockThreshold: 8,
    imports: [],
    sales: [],
    isHidden: false,
  },
  {
    id: 16,
    name: "Giày nam Warrior 2025 phong cách trẻ trung",
    categoryId: "C001",
    price: 522500,
    oldPrice: 550000,
    img: "./img/casual_Warrior.png",
    rating: 4,
    ratingCount: 89,
    badge: "sale",
    description:
      "Giày Warrior 2025 với phong cách trẻ trung, giá cả hợp lý, chất liệu nhẹ và bền, phù hợp cho sinh viên và giới trẻ năng động.",
    images: ["./img/casual_Warrior.png", "./img/casual_Warrior.png"],
    variants: [
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ],
    costPrice: 370000,
    initialStock: calculateInitialStock([
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ]),
    lowStockThreshold: 8,
    imports: [],
    sales: [],
    isHidden: false,
  },
  {
    id: 17,
    name: "Giày nam Warrior 2025 phong cách trẻ trung",
    categoryId: "C001",
    price: 522500,
    oldPrice: 550000,
    img: "./img/casual_Warrior.png",
    rating: 4,
    ratingCount: 89,
    badge: "sale",
    description:
      "Giày Warrior 2025 với phong cách trẻ trung, giá cả hợp lý, chất liệu nhẹ và bền, phù hợp cho sinh viên và giới trẻ năng động.",
    images: ["./img/casual_Warrior.png", "./img/casual_Warrior.png"],
    variants: [
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ],
    costPrice: 370000,
    initialStock: calculateInitialStock([
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ]),
    lowStockThreshold: 8,
    imports: [],
    sales: [],
    isHidden: false,
  },
  {
    id: 18,
    name: "Giày nam Warrior 2025 phong cách trẻ trung",
    categoryId: "C001",
    price: 522500,
    oldPrice: 550000,
    img: "./img/casual_Warrior.png",
    rating: 4,
    ratingCount: 89,
    badge: "sale",
    description:
      "Giày Warrior 2025 với phong cách trẻ trung, giá cả hợp lý, chất liệu nhẹ và bền, phù hợp cho sinh viên và giới trẻ năng động.",
    images: ["./img/casual_Warrior.png", "./img/casual_Warrior.png"],
    variants: [
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ],
    costPrice: 370000,
    initialStock: calculateInitialStock([
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ]),
    lowStockThreshold: 8,
    imports: [],
    sales: [],
    isHidden: false,
  },
  {
    id: 19,
    name: "Giày nam Warrior 2025 phong cách trẻ trung",
    categoryId: "C001",
    price: 522500,
    oldPrice: 550000,
    img: "./img/casual_Warrior.png",
    rating: 4,
    ratingCount: 89,
    badge: "sale",
    description:
      "Giày Warrior 2025 với phong cách trẻ trung, giá cả hợp lý, chất liệu nhẹ và bền, phù hợp cho sinh viên và giới trẻ năng động.",
    images: ["./img/casual_Warrior.png", "./img/casual_Warrior.png"],
    variants: [
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ],
    costPrice: 370000,
    initialStock: calculateInitialStock([
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ]),
    lowStockThreshold: 8,
    imports: [],
    sales: [],
    isHidden: false,
  },
  {
    id: 20,
    name: "Giày nam Warrior 2025 phong cách trẻ trung",
    categoryId: "C001",
    price: 522500,
    oldPrice: 550000,
    img: "./img/casual_Warrior.png",
    rating: 4,
    ratingCount: 89,
    badge: "sale",
    description:
      "Giày Warrior 2025 với phong cách trẻ trung, giá cả hợp lý, chất liệu nhẹ và bền, phù hợp cho sinh viên và giới trẻ năng động.",
    images: ["./img/casual_Warrior.png", "./img/casual_Warrior.png"],
    variants: [
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ],
    costPrice: 370000,
    initialStock: calculateInitialStock([
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ]),
    lowStockThreshold: 8,
    imports: [],
    sales: [],
    isHidden: false,
  },
  {
    id: 21,
    name: "Giày nam Warrior 2025 phong cách trẻ trung",
    categoryId: "C001",
    price: 522500,
    oldPrice: 550000,
    img: "./img/casual_Warrior.png",
    rating: 4,
    ratingCount: 89,
    badge: "sale",
    description:
      "Giày Warrior 2025 với phong cách trẻ trung, giá cả hợp lý, chất liệu nhẹ và bền, phù hợp cho sinh viên và giới trẻ năng động.",
    images: ["./img/casual_Warrior.png", "./img/casual_Warrior.png"],
    variants: [
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ],
    costPrice: 370000,
    initialStock: calculateInitialStock([
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ]),
    lowStockThreshold: 8,
    imports: [],
    sales: [],
    isHidden: false,
  },
  {
    id: 22,
    name: "Giày nam Warrior 2025 phong cách trẻ trung",
    categoryId: "C001",
    price: 522500,
    oldPrice: 550000,
    img: "./img/casual_Warrior.png",
    rating: 4,
    ratingCount: 89,
    badge: "sale",
    description:
      "Giày Warrior 2025 với phong cách trẻ trung, giá cả hợp lý, chất liệu nhẹ và bền, phù hợp cho sinh viên và giới trẻ năng động.",
    images: ["./img/casual_Warrior.png", "./img/casual_Warrior.png"],
    variants: [
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ],
    costPrice: 370000,
    initialStock: calculateInitialStock([
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ]),
    lowStockThreshold: 8,
    imports: [],
    sales: [],
    isHidden: false,
  },
  {
    id: 23,
    name: "Giày nam Warrior 2025 phong cách trẻ trung",
    categoryId: "C001",
    price: 522500,
    oldPrice: 550000,
    img: "./img/casual_Warrior.png",
    rating: 4,
    ratingCount: 89,
    badge: "sale",
    description:
      "Giày Warrior 2025 với phong cách trẻ trung, giá cả hợp lý, chất liệu nhẹ và bền, phù hợp cho sinh viên và giới trẻ năng động.",
    images: ["./img/casual_Warrior.png", "./img/casual_Warrior.png"],
    variants: [
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ],
    costPrice: 370000,
    initialStock: calculateInitialStock([
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ]),
    lowStockThreshold: 8,
    imports: [],
    sales: [],
    isHidden: false,
  },
  {
    id: 24,
    name: "Giày nam Warrior 2025 phong cách trẻ trung",
    categoryId: "C001",
    price: 522500,
    oldPrice: 550000,
    img: "./img/casual_Warrior.png",
    rating: 4,
    ratingCount: 89,
    badge: "sale",
    description:
      "Giày Warrior 2025 với phong cách trẻ trung, giá cả hợp lý, chất liệu nhẹ và bền, phù hợp cho sinh viên và giới trẻ năng động.",
    images: ["./img/casual_Warrior.png", "./img/casual_Warrior.png"],
    variants: [
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ],
    costPrice: 370000,
    initialStock: calculateInitialStock([
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ]),
    lowStockThreshold: 8,
    imports: [],
    sales: [],
    isHidden: false,
  },
  {
    id: 25,
    name: "Giày nam Warrior 2025 phong cách trẻ trung",
    categoryId: "C001",
    price: 522500,
    oldPrice: 550000,
    img: "./img/casual_Warrior.png",
    rating: 4,
    ratingCount: 89,
    badge: "sale",
    description:
      "Giày Warrior 2025 với phong cách trẻ trung, giá cả hợp lý, chất liệu nhẹ và bền, phù hợp cho sinh viên và giới trẻ năng động.",
    images: ["./img/casual_Warrior.png", "./img/casual_Warrior.png"],
    variants: [
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ],
    costPrice: 370000,
    initialStock: calculateInitialStock([
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ]),
    lowStockThreshold: 8,
    imports: [],
    sales: [],
    isHidden: false,
  },
  {
    id: 26,
    name: "Giày nam Warrior 2025 phong cách trẻ trung",
    categoryId: "C001",
    price: 522500,
    oldPrice: 550000,
    img: "./img/casual_Warrior.png",
    rating: 4,
    ratingCount: 89,
    badge: "sale",
    description:
      "Giày Warrior 2025 với phong cách trẻ trung, giá cả hợp lý, chất liệu nhẹ và bền, phù hợp cho sinh viên và giới trẻ năng động.",
    images: ["./img/casual_Warrior.png", "./img/casual_Warrior.png"],
    variants: [
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ],
    costPrice: 370000,
    initialStock: calculateInitialStock([
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ]),
    lowStockThreshold: 8,
    imports: [],
    sales: [],
    isHidden: false,
  },
  {
    id: 27,
    name: "Giày nam Warrior 2025 phong cách trẻ trung",
    categoryId: "C001",
    price: 522500,
    oldPrice: 550000,
    img: "./img/casual_Warrior.png",
    rating: 4,
    ratingCount: 89,
    badge: "sale",
    description:
      "Giày Warrior 2025 với phong cách trẻ trung, giá cả hợp lý, chất liệu nhẹ và bền, phù hợp cho sinh viên và giới trẻ năng động.",
    images: ["./img/casual_Warrior.png", "./img/casual_Warrior.png"],
    variants: [
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ],
    costPrice: 370000,
    initialStock: calculateInitialStock([
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ]),
    lowStockThreshold: 8,
    imports: [],
    sales: [],
    isHidden: false,
  },
  {
    id: 28,
    name: "Giày nam Warrior 2025 phong cách trẻ trung",
    categoryId: "C001",
    price: 522500,
    oldPrice: 550000,
    img: "./img/casual_Warrior.png",
    rating: 4,
    ratingCount: 89,
    badge: "sale",
    description:
      "Giày Warrior 2025 với phong cách trẻ trung, giá cả hợp lý, chất liệu nhẹ và bền, phù hợp cho sinh viên và giới trẻ năng động.",
    images: ["./img/casual_Warrior.png", "./img/casual_Warrior.png"],
    variants: [
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ],
    costPrice: 370000,
    initialStock: calculateInitialStock([
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ]),
    lowStockThreshold: 8,
    imports: [],
    sales: [],
    isHidden: false,
  },
  {
    id: 29,
    name: "Giày nam Warrior 2025 phong cách trẻ trung",
    categoryId: "C001",
    price: 522500,
    oldPrice: 550000,
    img: "./img/casual_Warrior.png",
    rating: 4,
    ratingCount: 89,
    badge: "sale",
    description:
      "Giày Warrior 2025 với phong cách trẻ trung, giá cả hợp lý, chất liệu nhẹ và bền, phù hợp cho sinh viên và giới trẻ năng động.",
    images: ["./img/casual_Warrior.png", "./img/casual_Warrior.png"],
    variants: [
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ],
    costPrice: 370000,
    initialStock: calculateInitialStock([
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ]),
    lowStockThreshold: 8,
    imports: [],
    sales: [],
    isHidden: false,
  },
  {
    id: 30,
    name: "Giày nam Warrior 2025 phong cách trẻ trung",
    categoryId: "C001",
    price: 522500,
    oldPrice: 550000,
    img: "./img/casual_Warrior.png",
    rating: 4,
    ratingCount: 89,
    badge: "sale",
    description:
      "Giày Warrior 2025 với phong cách trẻ trung, giá cả hợp lý, chất liệu nhẹ và bền, phù hợp cho sinh viên và giới trẻ năng động.",
    images: ["./img/casual_Warrior.png", "./img/casual_Warrior.png"],
    variants: [
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ],
    costPrice: 370000,
    initialStock: calculateInitialStock([
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ]),
    lowStockThreshold: 8,
    imports: [],
    sales: [],
    isHidden: false,
  },
  {
    id: 31,
    name: "Giày nam Warrior 2025 phong cách trẻ trung",
    categoryId: "C001",
    price: 522500,
    oldPrice: 550000,
    img: "./img/casual_Warrior.png",
    rating: 4,
    ratingCount: 89,
    badge: "sale",
    description:
      "Giày Warrior 2025 với phong cách trẻ trung, giá cả hợp lý, chất liệu nhẹ và bền, phù hợp cho sinh viên và giới trẻ năng động.",
    images: ["./img/casual_Warrior.png", "./img/casual_Warrior.png"],
    variants: [
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ],
    costPrice: 370000,
    initialStock: calculateInitialStock([
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ]),
    lowStockThreshold: 8,
    imports: [],
    sales: [],
    isHidden: false,
  },
  {
    id: 32,
    name: "Giày nam Warrior 2025 phong cách trẻ trung",
    categoryId: "C001",
    price: 522500,
    oldPrice: 550000,
    img: "./img/casual_Warrior.png",
    rating: 4,
    ratingCount: 89,
    badge: "sale",
    description:
      "Giày Warrior 2025 với phong cách trẻ trung, giá cả hợp lý, chất liệu nhẹ và bền, phù hợp cho sinh viên và giới trẻ năng động.",
    images: ["./img/casual_Warrior.png", "./img/casual_Warrior.png"],
    variants: [
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ],
    costPrice: 370000,
    initialStock: calculateInitialStock([
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ]),
    lowStockThreshold: 8,
    imports: [],
    sales: [],
    isHidden: false,
  },
  {
    id: 33,
    name: "Giày nam Warrior 2025 phong cách trẻ trung",
    categoryId: "C001",
    price: 522500,
    oldPrice: 550000,
    img: "./img/casual_Warrior.png",
    rating: 4,
    ratingCount: 89,
    badge: "sale",
    description:
      "Giày Warrior 2025 với phong cách trẻ trung, giá cả hợp lý, chất liệu nhẹ và bền, phù hợp cho sinh viên và giới trẻ năng động.",
    images: ["./img/casual_Warrior.png", "./img/casual_Warrior.png"],
    variants: [
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ],
    costPrice: 370000,
    initialStock: calculateInitialStock([
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ]),
    lowStockThreshold: 8,
    imports: [],
    sales: [],
    isHidden: false,
  },
  {
    id: 34,
    name: "Giày nam Warrior 2025 phong cách trẻ trung",
    categoryId: "C001",
    price: 522500,
    oldPrice: 550000,
    img: "./img/casual_Warrior.png",
    rating: 4,
    ratingCount: 89,
    badge: "sale",
    description:
      "Giày Warrior 2025 với phong cách trẻ trung, giá cả hợp lý, chất liệu nhẹ và bền, phù hợp cho sinh viên và giới trẻ năng động.",
    images: ["./img/casual_Warrior.png", "./img/casual_Warrior.png"],
    variants: [
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ],
    costPrice: 370000,
    initialStock: calculateInitialStock([
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ]),
    lowStockThreshold: 8,
    imports: [],
    sales: [],
    isHidden: false,
  },
  {
    id: 35,
    name: "Giày nam Warrior 2025 phong cách trẻ trung",
    categoryId: "C001",
    price: 522500,
    oldPrice: 550000,
    img: "./img/casual_Warrior.png",
    rating: 4,
    ratingCount: 89,
    badge: "sale",
    description:
      "Giày Warrior 2025 với phong cách trẻ trung, giá cả hợp lý, chất liệu nhẹ và bền, phù hợp cho sinh viên và giới trẻ năng động.",
    images: ["./img/casual_Warrior.png", "./img/casual_Warrior.png"],
    variants: [
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ],
    costPrice: 370000,
    initialStock: calculateInitialStock([
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ]),
    lowStockThreshold: 8,
    imports: [],
    sales: [],
    isHidden: false,
  },
  {
    id: 36,
    name: "Giày nam Warrior 2025 phong cách trẻ trung",
    categoryId: "C001",
    price: 522500,
    oldPrice: 550000,
    img: "./img/casual_Warrior.png",
    rating: 4,
    ratingCount: 89,
    badge: "sale",
    description:
      "Giày Warrior 2025 với phong cách trẻ trung, giá cả hợp lý, chất liệu nhẹ và bền, phù hợp cho sinh viên và giới trẻ năng động.",
    images: ["./img/casual_Warrior.png", "./img/casual_Warrior.png"],
    variants: [
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ],
    costPrice: 370000,
    initialStock: calculateInitialStock([
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ]),
    lowStockThreshold: 8,
    imports: [],
    sales: [],
    isHidden: false,
  },
  {
    id: 37,
    name: "Giày nam Warrior 2025 phong cách trẻ trung",
    categoryId: "C001",
    price: 522500,
    oldPrice: 550000,
    img: "./img/casual_Warrior.png",
    rating: 4,
    ratingCount: 89,
    badge: "sale",
    description:
      "Giày Warrior 2025 với phong cách trẻ trung, giá cả hợp lý, chất liệu nhẹ và bền, phù hợp cho sinh viên và giới trẻ năng động.",
    images: ["./img/casual_Warrior.png", "./img/casual_Warrior.png"],
    variants: [
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ],
    costPrice: 370000,
    initialStock: calculateInitialStock([
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ]),
    lowStockThreshold: 8,
    imports: [],
    sales: [],
    isHidden: false,
  },
  {
    id: 38,
    name: "Giày nam Warrior 2025 phong cách trẻ trung",
    categoryId: "C001",
    price: 522500,
    oldPrice: 550000,
    img: "./img/casual_Warrior.png",
    rating: 4,
    ratingCount: 89,
    badge: "sale",
    description:
      "Giày Warrior 2025 với phong cách trẻ trung, giá cả hợp lý, chất liệu nhẹ và bền, phù hợp cho sinh viên và giới trẻ năng động.",
    images: ["./img/casual_Warrior.png", "./img/casual_Warrior.png"],
    variants: [
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ],
    costPrice: 370000,
    initialStock: calculateInitialStock([
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ]),
    lowStockThreshold: 8,
    imports: [],
    sales: [],
    isHidden: false,
  },
  {
    id: 39,
    name: "Giày nam Warrior 2025 phong cách trẻ trung",
    categoryId: "C001",
    price: 522500,
    oldPrice: 550000,
    img: "./img/casual_Warrior.png",
    rating: 4,
    ratingCount: 89,
    badge: "sale",
    description:
      "Giày Warrior 2025 với phong cách trẻ trung, giá cả hợp lý, chất liệu nhẹ và bền, phù hợp cho sinh viên và giới trẻ năng động.",
    images: ["./img/casual_Warrior.png", "./img/casual_Warrior.png"],
    variants: [
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ],
    costPrice: 370000,
    initialStock: calculateInitialStock([
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ]),
    lowStockThreshold: 8,
    imports: [],
    sales: [],
    isHidden: false,
  },
  {
    id: 40,
    name: "Giày nam Warrior 2025 phong cách trẻ trung",
    categoryId: "C001",
    price: 522500,
    oldPrice: 550000,
    img: "./img/casual_Warrior.png",
    rating: 4,
    ratingCount: 89,
    badge: "sale",
    description:
      "Giày Warrior 2025 với phong cách trẻ trung, giá cả hợp lý, chất liệu nhẹ và bền, phù hợp cho sinh viên và giới trẻ năng động.",
    images: ["./img/casual_Warrior.png", "./img/casual_Warrior.png"],
    variants: [
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ],
    costPrice: 370000,
    initialStock: calculateInitialStock([
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ]),
    lowStockThreshold: 8,
    imports: [],
    sales: [],
    isHidden: false,
  },
  {
    id: 41,
    name: "Giày nam Warrior 2025 phong cách trẻ trung",
    categoryId: "C001",
    price: 522500,
    oldPrice: 550000,
    img: "./img/casual_Warrior.png",
    rating: 4,
    ratingCount: 89,
    badge: "sale",
    description:
      "Giày Warrior 2025 với phong cách trẻ trung, giá cả hợp lý, chất liệu nhẹ và bền, phù hợp cho sinh viên và giới trẻ năng động.",
    images: ["./img/casual_Warrior.png", "./img/casual_Warrior.png"],
    variants: [
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ],
    costPrice: 370000,
    initialStock: calculateInitialStock([
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ]),
    lowStockThreshold: 8,
    imports: [],
    sales: [],
    isHidden: false,
  },
  {
    id: 42,
    name: "Giày nam Warrior 2025 phong cách trẻ trung",
    categoryId: "C001",
    price: 522500,
    oldPrice: 550000,
    img: "./img/casual_Warrior.png",
    rating: 4,
    ratingCount: 89,
    badge: "sale",
    description:
      "Giày Warrior 2025 với phong cách trẻ trung, giá cả hợp lý, chất liệu nhẹ và bền, phù hợp cho sinh viên và giới trẻ năng động.",
    images: ["./img/casual_Warrior.png", "./img/casual_Warrior.png"],
    variants: [
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ],
    costPrice: 370000,
    initialStock: calculateInitialStock([
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ]),
    lowStockThreshold: 8,
    imports: [],
    sales: [],
    isHidden: false,
  },
  {
    id: 43,
    name: "Giày nam Warrior 2025 phong cách trẻ trung",
    categoryId: "C001",
    price: 522500,
    oldPrice: 550000,
    img: "./img/casual_Warrior.png",
    rating: 4,
    ratingCount: 89,
    badge: "sale",
    description:
      "Giày Warrior 2025 với phong cách trẻ trung, giá cả hợp lý, chất liệu nhẹ và bền, phù hợp cho sinh viên và giới trẻ năng động.",
    images: ["./img/casual_Warrior.png", "./img/casual_Warrior.png"],
    variants: [
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ],
    costPrice: 370000,
    initialStock: calculateInitialStock([
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ]),
    lowStockThreshold: 8,
    imports: [],
    sales: [],
    isHidden: false,
  },
  {
    id: 44,
    name: "Giày nam Warrior 2025 phong cách trẻ trung",
    categoryId: "C001",
    price: 522500,
    oldPrice: 550000,
    img: "./img/casual_Warrior.png",
    rating: 4,
    ratingCount: 89,
    badge: "sale",
    description:
      "Giày Warrior 2025 với phong cách trẻ trung, giá cả hợp lý, chất liệu nhẹ và bền, phù hợp cho sinh viên và giới trẻ năng động.",
    images: ["./img/casual_Warrior.png", "./img/casual_Warrior.png"],
    variants: [
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ],
    costPrice: 370000,
    initialStock: calculateInitialStock([
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ]),
    lowStockThreshold: 8,
    imports: [],
    sales: [],
    isHidden: false,
  },
  {
    id: 45,
    name: "Giày nam Warrior 2025 phong cách trẻ trung",
    categoryId: "C001",
    price: 522500,
    oldPrice: 550000,
    img: "./img/casual_Warrior.png",
    rating: 4,
    ratingCount: 89,
    badge: "sale",
    description:
      "Giày Warrior 2025 với phong cách trẻ trung, giá cả hợp lý, chất liệu nhẹ và bền, phù hợp cho sinh viên và giới trẻ năng động.",
    images: ["./img/casual_Warrior.png", "./img/casual_Warrior.png"],
    variants: [
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ],
    costPrice: 370000,
    initialStock: calculateInitialStock([
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ]),
    lowStockThreshold: 8,
    imports: [],
    sales: [],
    isHidden: false,
  },
  {
    id: 46,
    name: "Giày nam Warrior 2025 phong cách trẻ trung",
    categoryId: "C001",
    price: 522500,
    oldPrice: 550000,
    img: "./img/casual_Warrior.png",
    rating: 4,
    ratingCount: 89,
    badge: "sale",
    description:
      "Giày Warrior 2025 với phong cách trẻ trung, giá cả hợp lý, chất liệu nhẹ và bền, phù hợp cho sinh viên và giới trẻ năng động.",
    images: ["./img/casual_Warrior.png", "./img/casual_Warrior.png"],
    variants: [
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ],
    costPrice: 370000,
    initialStock: calculateInitialStock([
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ]),
    lowStockThreshold: 8,
    imports: [],
    sales: [],
    isHidden: false,
  },
  {
    id: 47,
    name: "Giày nam Warrior 2025 phong cách trẻ trung",
    categoryId: "C001",
    price: 522500,
    oldPrice: 550000,
    img: "./img/casual_Warrior.png",
    rating: 4,
    ratingCount: 89,
    badge: "sale",
    description:
      "Giày Warrior 2025 với phong cách trẻ trung, giá cả hợp lý, chất liệu nhẹ và bền, phù hợp cho sinh viên và giới trẻ năng động.",
    images: ["./img/casual_Warrior.png", "./img/casual_Warrior.png"],
    variants: [
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ],
    costPrice: 370000,
    initialStock: calculateInitialStock([
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ]),
    lowStockThreshold: 8,
    imports: [],
    sales: [],
    isHidden: false,
  },
  {
    id: 48,
    name: "Giày nam Warrior 2025 phong cách trẻ trung",
    categoryId: "C001",
    price: 522500,
    oldPrice: 550000,
    img: "./img/casual_Warrior.png",
    rating: 4,
    ratingCount: 89,
    badge: "sale",
    description:
      "Giày Warrior 2025 với phong cách trẻ trung, giá cả hợp lý, chất liệu nhẹ và bền, phù hợp cho sinh viên và giới trẻ năng động.",
    images: ["./img/casual_Warrior.png", "./img/casual_Warrior.png"],
    variants: [
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ],
    costPrice: 370000,
    initialStock: calculateInitialStock([
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ]),
    lowStockThreshold: 8,
    imports: [],
    sales: [],
    isHidden: false,
  },
  {
    id: 49,
    name: "Giày nam Warrior 2025 phong cách trẻ trung",
    categoryId: "C001",
    price: 522500,
    oldPrice: 550000,
    img: "./img/casual_Warrior.png",
    rating: 4,
    ratingCount: 89,
    badge: "sale",
    description:
      "Giày Warrior 2025 với phong cách trẻ trung, giá cả hợp lý, chất liệu nhẹ và bền, phù hợp cho sinh viên và giới trẻ năng động.",
    images: ["./img/casual_Warrior.png", "./img/casual_Warrior.png"],
    variants: [
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ],
    costPrice: 370000,
    initialStock: calculateInitialStock([
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ]),
    lowStockThreshold: 8,
    imports: [],
    sales: [],
    isHidden: false,
  },
  {
    id: 50,
    name: "Giày nam Warrior 2025 phong cách trẻ trung",
    categoryId: "C001",
    price: 522500,
    oldPrice: 550000,
    img: "./img/casual_Warrior.png",
    rating: 4,
    ratingCount: 89,
    badge: "sale",
    description:
      "Giày Warrior 2025 với phong cách trẻ trung, giá cả hợp lý, chất liệu nhẹ và bền, phù hợp cho sinh viên và giới trẻ năng động.",
    images: ["./img/casual_Warrior.png", "./img/casual_Warrior.png"],
    variants: [
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ],
    costPrice: 370000,
    initialStock: calculateInitialStock([
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ]),
    lowStockThreshold: 8,
    imports: [],
    sales: [],
    isHidden: false,
  },
  {
    id: 51,
    name: "Giày nam Warrior 2025 phong cách trẻ trung",
    categoryId: "C001",
    price: 522500,
    oldPrice: 550000,
    img: "./img/casual_Warrior.png",
    rating: 4,
    ratingCount: 89,
    badge: "sale",
    description:
      "Giày Warrior 2025 với phong cách trẻ trung, giá cả hợp lý, chất liệu nhẹ và bền, phù hợp cho sinh viên và giới trẻ năng động.",
    images: ["./img/casual_Warrior.png", "./img/casual_Warrior.png"],
    variants: [
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ],
    costPrice: 370000,
    initialStock: calculateInitialStock([
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ]),
    lowStockThreshold: 8,
    imports: [],
    sales: [],
    isHidden: false,
  },
  {
    id: 52,
    name: "Giày nam Warrior 2025 phong cách trẻ trung",
    categoryId: "C001",
    price: 522500,
    oldPrice: 550000,
    img: "./img/casual_Warrior.png",
    rating: 4,
    ratingCount: 89,
    badge: "sale",
    description:
      "Giày Warrior 2025 với phong cách trẻ trung, giá cả hợp lý, chất liệu nhẹ và bền, phù hợp cho sinh viên và giới trẻ năng động.",
    images: ["./img/casual_Warrior.png", "./img/casual_Warrior.png"],
    variants: [
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ],
    costPrice: 370000,
    initialStock: calculateInitialStock([
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ]),
    lowStockThreshold: 8,
    imports: [],
    sales: [],
    isHidden: false,
  },
  {
    id: 53,
    name: "Giày nam Warrior 2025 phong cách trẻ trung",
    categoryId: "C001",
    price: 522500,
    oldPrice: 550000,
    img: "./img/casual_Warrior.png",
    rating: 4,
    ratingCount: 89,
    badge: "sale",
    description:
      "Giày Warrior 2025 với phong cách trẻ trung, giá cả hợp lý, chất liệu nhẹ và bền, phù hợp cho sinh viên và giới trẻ năng động.",
    images: ["./img/casual_Warrior.png", "./img/casual_Warrior.png"],
    variants: [
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ],
    costPrice: 370000,
    initialStock: calculateInitialStock([
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ]),
    lowStockThreshold: 8,
    imports: [],
    sales: [],
    isHidden: false,
  },
  {
    id: 54,
    name: "Giày nam Warrior 2025 phong cách trẻ trung",
    categoryId: "C001",
    price: 522500,
    oldPrice: 550000,
    img: "./img/casual_Warrior.png",
    rating: 4,
    ratingCount: 89,
    badge: "sale",
    description:
      "Giày Warrior 2025 với phong cách trẻ trung, giá cả hợp lý, chất liệu nhẹ và bền, phù hợp cho sinh viên và giới trẻ năng động.",
    images: ["./img/casual_Warrior.png", "./img/casual_Warrior.png"],
    variants: [
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ],
    costPrice: 370000,
    initialStock: calculateInitialStock([
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ]),
    lowStockThreshold: 8,
    imports: [],
    sales: [],
    isHidden: false,
  },
  {
    id: 55,
    name: "Giày nam Warrior 2025 phong cách trẻ trung",
    categoryId: "C001",
    price: 522500,
    oldPrice: 550000,
    img: "./img/casual_Warrior.png",
    rating: 4,
    ratingCount: 89,
    badge: "sale",
    description:
      "Giày Warrior 2025 với phong cách trẻ trung, giá cả hợp lý, chất liệu nhẹ và bền, phù hợp cho sinh viên và giới trẻ năng động.",
    images: ["./img/casual_Warrior.png", "./img/casual_Warrior.png"],
    variants: [
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ],
    costPrice: 370000,
    initialStock: calculateInitialStock([
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ]),
    lowStockThreshold: 8,
    imports: [],
    sales: [],
    isHidden: false,
  },
  {
    id: 56,
    name: "Giày nam Warrior 2025 phong cách trẻ trung",
    categoryId: "C001",
    price: 522500,
    oldPrice: 550000,
    img: "./img/casual_Warrior.png",
    rating: 4,
    ratingCount: 89,
    badge: "sale",
    description:
      "Giày Warrior 2025 với phong cách trẻ trung, giá cả hợp lý, chất liệu nhẹ và bền, phù hợp cho sinh viên và giới trẻ năng động.",
    images: ["./img/casual_Warrior.png", "./img/casual_Warrior.png"],
    variants: [
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ],
    costPrice: 370000,
    initialStock: calculateInitialStock([
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ]),
    lowStockThreshold: 8,
    imports: [],
    sales: [],
    isHidden: false,
  },
  {
    id: 57,
    name: "Giày nam Warrior 2025 phong cách trẻ trung",
    categoryId: "C001",
    price: 522500,
    oldPrice: 550000,
    img: "./img/casual_Warrior.png",
    rating: 4,
    ratingCount: 89,
    badge: "sale",
    description:
      "Giày Warrior 2025 với phong cách trẻ trung, giá cả hợp lý, chất liệu nhẹ và bền, phù hợp cho sinh viên và giới trẻ năng động.",
    images: ["./img/casual_Warrior.png", "./img/casual_Warrior.png"],
    variants: [
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ],
    costPrice: 370000,
    initialStock: calculateInitialStock([
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ]),
    lowStockThreshold: 8,
    imports: [],
    sales: [],
    isHidden: false,
  },
  {
    id: 58,
    name: "Giày nam Warrior 2025 phong cách trẻ trung",
    categoryId: "C001",
    price: 522500,
    oldPrice: 550000,
    img: "./img/casual_Warrior.png",
    rating: 4,
    ratingCount: 89,
    badge: "sale",
    description:
      "Giày Warrior 2025 với phong cách trẻ trung, giá cả hợp lý, chất liệu nhẹ và bền, phù hợp cho sinh viên và giới trẻ năng động.",
    images: ["./img/casual_Warrior.png", "./img/casual_Warrior.png"],
    variants: [
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ],
    costPrice: 370000,
    initialStock: calculateInitialStock([
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ]),
    lowStockThreshold: 8,
    imports: [],
    sales: [],
    isHidden: false,
  },
  {
    id: 59,
    name: "Giày nam Warrior 2025 phong cách trẻ trung",
    categoryId: "C001",
    price: 522500,
    oldPrice: 550000,
    img: "./img/casual_Warrior.png",
    rating: 4,
    ratingCount: 89,
    badge: "sale",
    description:
      "Giày Warrior 2025 với phong cách trẻ trung, giá cả hợp lý, chất liệu nhẹ và bền, phù hợp cho sinh viên và giới trẻ năng động.",
    images: ["./img/casual_Warrior.png", "./img/casual_Warrior.png"],
    variants: [
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ],
    costPrice: 370000,
    initialStock: calculateInitialStock([
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ]),
    lowStockThreshold: 8,
    imports: [],
    sales: [],
    isHidden: false,
  },
  {
    id: 60,
    name: "Giày nam Warrior 2025 phong cách trẻ trung",
    categoryId: "C001",
    price: 522500,
    oldPrice: 550000,
    img: "./img/casual_Warrior.png",
    rating: 4,
    ratingCount: 89,
    badge: "sale",
    description:
      "Giày Warrior 2025 với phong cách trẻ trung, giá cả hợp lý, chất liệu nhẹ và bền, phù hợp cho sinh viên và giới trẻ năng động.",
    images: ["./img/casual_Warrior.png", "./img/casual_Warrior.png"],
    variants: [
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ],
    costPrice: 370000,
    initialStock: calculateInitialStock([
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ]),
    lowStockThreshold: 8,
    imports: [],
    sales: [],
    isHidden: false,
  },
  {
    id: 61,
    name: "Giày nam Warrior 2025 phong cách trẻ trung",
    categoryId: "C001",
    price: 522500,
    oldPrice: 550000,
    img: "./img/casual_Warrior.png",
    rating: 4,
    ratingCount: 89,
    badge: "sale",
    description:
      "Giày Warrior 2025 với phong cách trẻ trung, giá cả hợp lý, chất liệu nhẹ và bền, phù hợp cho sinh viên và giới trẻ năng động.",
    images: ["./img/casual_Warrior.png", "./img/casual_Warrior.png"],
    variants: [
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ],
    costPrice: 370000,
    initialStock: calculateInitialStock([
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ]),
    lowStockThreshold: 8,
    imports: [],
    sales: [],
    isHidden: false,
  },
  {
    id: 62,
    name: "Giày nam Warrior 2025 phong cách trẻ trung",
    categoryId: "C001",
    price: 522500,
    oldPrice: 550000,
    img: "./img/casual_Warrior.png",
    rating: 4,
    ratingCount: 89,
    badge: "sale",
    description:
      "Giày Warrior 2025 với phong cách trẻ trung, giá cả hợp lý, chất liệu nhẹ và bền, phù hợp cho sinh viên và giới trẻ năng động.",
    images: ["./img/casual_Warrior.png", "./img/casual_Warrior.png"],
    variants: [
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ],
    costPrice: 370000,
    initialStock: calculateInitialStock([
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ]),
    lowStockThreshold: 8,
    imports: [],
    sales: [],
    isHidden: false,
  },
  {
    id: 63,
    name: "Giày nam Warrior 2025 phong cách trẻ trung",
    categoryId: "C001",
    price: 522500,
    oldPrice: 550000,
    img: "./img/casual_Warrior.png",
    rating: 4,
    ratingCount: 89,
    badge: "sale",
    description:
      "Giày Warrior 2025 với phong cách trẻ trung, giá cả hợp lý, chất liệu nhẹ và bền, phù hợp cho sinh viên và giới trẻ năng động.",
    images: ["./img/casual_Warrior.png", "./img/casual_Warrior.png"],
    variants: [
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ],
    costPrice: 370000,
    initialStock: calculateInitialStock([
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ]),
    lowStockThreshold: 8,
    imports: [],
    sales: [],
    isHidden: false,
  },
  {
    id: 64,
    name: "Giày nam Warrior 2025 phong cách trẻ trung",
    categoryId: "C001",
    price: 522500,
    oldPrice: 550000,
    img: "./img/casual_Warrior.png",
    rating: 4,
    ratingCount: 89,
    badge: "sale",
    description:
      "Giày Warrior 2025 với phong cách trẻ trung, giá cả hợp lý, chất liệu nhẹ và bền, phù hợp cho sinh viên và giới trẻ năng động.",
    images: ["./img/casual_Warrior.png", "./img/casual_Warrior.png"],
    variants: [
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ],
    costPrice: 370000,
    initialStock: calculateInitialStock([
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ]),
    lowStockThreshold: 8,
    imports: [],
    sales: [],
    isHidden: false,
  },
  {
    id: 65,
    name: "Giày nam Warrior 2025 phong cách trẻ trung",
    categoryId: "C001",
    price: 522500,
    oldPrice: 550000,
    img: "./img/casual_Warrior.png",
    rating: 4,
    ratingCount: 89,
    badge: "sale",
    description:
      "Giày Warrior 2025 với phong cách trẻ trung, giá cả hợp lý, chất liệu nhẹ và bền, phù hợp cho sinh viên và giới trẻ năng động.",
    images: ["./img/casual_Warrior.png", "./img/casual_Warrior.png"],
    variants: [
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ],
    costPrice: 370000,
    initialStock: calculateInitialStock([
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ]),
    lowStockThreshold: 8,
    imports: [],
    sales: [],
    isHidden: false,
  },
  {
    id: 66,
    name: "Giày nam Warrior 2025 phong cách trẻ trung",
    categoryId: "C001",
    price: 522500,
    oldPrice: 550000,
    img: "./img/casual_Warrior.png",
    rating: 4,
    ratingCount: 89,
    badge: "sale",
    description:
      "Giày Warrior 2025 với phong cách trẻ trung, giá cả hợp lý, chất liệu nhẹ và bền, phù hợp cho sinh viên và giới trẻ năng động.",
    images: ["./img/casual_Warrior.png", "./img/casual_Warrior.png"],
    variants: [
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ],
    costPrice: 370000,
    initialStock: calculateInitialStock([
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ]),
    lowStockThreshold: 8,
    imports: [],
    sales: [],
    isHidden: false,
  },
  {
    id: 67,
    name: "Giày nam Warrior 2025 phong cách trẻ trung",
    categoryId: "C001",
    price: 522500,
    oldPrice: 550000,
    img: "./img/casual_Warrior.png",
    rating: 4,
    ratingCount: 89,
    badge: "sale",
    description:
      "Giày Warrior 2025 với phong cách trẻ trung, giá cả hợp lý, chất liệu nhẹ và bền, phù hợp cho sinh viên và giới trẻ năng động.",
    images: ["./img/casual_Warrior.png", "./img/casual_Warrior.png"],
    variants: [
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ],
    costPrice: 370000,
    initialStock: calculateInitialStock([
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ]),
    lowStockThreshold: 8,
    imports: [],
    sales: [],
    isHidden: false,
  },
  {
    id: 68,
    name: "Giày nam Warrior 2025 phong cách trẻ trung",
    categoryId: "C001",
    price: 522500,
    oldPrice: 550000,
    img: "./img/casual_Warrior.png",
    rating: 4,
    ratingCount: 89,
    badge: "sale",
    description:
      "Giày Warrior 2025 với phong cách trẻ trung, giá cả hợp lý, chất liệu nhẹ và bền, phù hợp cho sinh viên và giới trẻ năng động.",
    images: ["./img/casual_Warrior.png", "./img/casual_Warrior.png"],
    variants: [
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ],
    costPrice: 370000,
    initialStock: calculateInitialStock([
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ]),
    lowStockThreshold: 8,
    imports: [],
    sales: [],
    isHidden: false,
  },
  {
    id: 69,
    name: "Giày nam Warrior 2025 phong cách trẻ trung",
    categoryId: "C001",
    price: 522500,
    oldPrice: 550000,
    img: "./img/casual_Warrior.png",
    rating: 4,
    ratingCount: 89,
    badge: "sale",
    description:
      "Giày Warrior 2025 với phong cách trẻ trung, giá cả hợp lý, chất liệu nhẹ và bền, phù hợp cho sinh viên và giới trẻ năng động.",
    images: ["./img/casual_Warrior.png", "./img/casual_Warrior.png"],
    variants: [
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ],
    costPrice: 370000,
    initialStock: calculateInitialStock([
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ]),
    lowStockThreshold: 8,
    imports: [],
    sales: [],
    isHidden: false,
  },
  {
    id: 70,
    name: "Giày nam Warrior 2025 phong cách trẻ trung",
    categoryId: "C001",
    price: 522500,
    oldPrice: 550000,
    img: "./img/casual_Warrior.png",
    rating: 4,
    ratingCount: 89,
    badge: "sale",
    description:
      "Giày Warrior 2025 với phong cách trẻ trung, giá cả hợp lý, chất liệu nhẹ và bền, phù hợp cho sinh viên và giới trẻ năng động.",
    images: ["./img/casual_Warrior.png", "./img/casual_Warrior.png"],
    variants: [
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ],
    costPrice: 370000,
    initialStock: calculateInitialStock([
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ]),
    lowStockThreshold: 8,
    imports: [],
    sales: [],
    isHidden: false,
  },
  {
    id: 71,
    name: "Giày nam Warrior 2025 phong cách trẻ trung",
    categoryId: "C001",
    price: 522500,
    oldPrice: 550000,
    img: "./img/casual_Warrior.png",
    rating: 4,
    ratingCount: 89,
    badge: "sale",
    description:
      "Giày Warrior 2025 với phong cách trẻ trung, giá cả hợp lý, chất liệu nhẹ và bền, phù hợp cho sinh viên và giới trẻ năng động.",
    images: ["./img/casual_Warrior.png", "./img/casual_Warrior.png"],
    variants: [
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ],
    costPrice: 370000,
    initialStock: calculateInitialStock([
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ]),
    lowStockThreshold: 8,
    imports: [],
    sales: [],
    isHidden: false,
  },
  {
    id: 72,
    name: "Giày nam Warrior 2025 phong cách trẻ trung",
    categoryId: "C001",
    price: 522500,
    oldPrice: 550000,
    img: "./img/casual_Warrior.png",
    rating: 4,
    ratingCount: 89,
    badge: "sale",
    description:
      "Giày Warrior 2025 với phong cách trẻ trung, giá cả hợp lý, chất liệu nhẹ và bền, phù hợp cho sinh viên và giới trẻ năng động.",
    images: ["./img/casual_Warrior.png", "./img/casual_Warrior.png"],
    variants: [
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ],
    costPrice: 370000,
    initialStock: calculateInitialStock([
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ]),
    lowStockThreshold: 8,
    imports: [],
    sales: [],
    isHidden: false,
  },
  {
    id: 73,
    name: "Giày nam Warrior 2025 phong cách trẻ trung",
    categoryId: "C001",
    price: 522500,
    oldPrice: 550000,
    img: "./img/casual_Warrior.png",
    rating: 4,
    ratingCount: 89,
    badge: "sale",
    description:
      "Giày Warrior 2025 với phong cách trẻ trung, giá cả hợp lý, chất liệu nhẹ và bền, phù hợp cho sinh viên và giới trẻ năng động.",
    images: ["./img/casual_Warrior.png", "./img/casual_Warrior.png"],
    variants: [
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ],
    costPrice: 370000,
    initialStock: calculateInitialStock([
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ]),
    lowStockThreshold: 8,
    imports: [],
    sales: [],
    isHidden: false,
  },
  {
    id: 74,
    name: "Giày nam Warrior 2025 phong cách trẻ trung",
    categoryId: "C001",
    price: 522500,
    oldPrice: 550000,
    img: "./img/casual_Warrior.png",
    rating: 4,
    ratingCount: 89,
    badge: "sale",
    description:
      "Giày Warrior 2025 với phong cách trẻ trung, giá cả hợp lý, chất liệu nhẹ và bền, phù hợp cho sinh viên và giới trẻ năng động.",
    images: ["./img/casual_Warrior.png", "./img/casual_Warrior.png"],
    variants: [
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ],
    costPrice: 370000,
    initialStock: calculateInitialStock([
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ]),
    lowStockThreshold: 8,
    imports: [],
    sales: [],
    isHidden: false,
  },
  {
    id: 75,
    name: "Giày nam Warrior 2025 phong cách trẻ trung",
    categoryId: "C001",
    price: 522500,
    oldPrice: 550000,
    img: "./img/casual_Warrior.png",
    rating: 4,
    ratingCount: 89,
    badge: "sale",
    description:
      "Giày Warrior 2025 với phong cách trẻ trung, giá cả hợp lý, chất liệu nhẹ và bền, phù hợp cho sinh viên và giới trẻ năng động.",
    images: ["./img/casual_Warrior.png", "./img/casual_Warrior.png"],
    variants: [
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ],
    costPrice: 370000,
    initialStock: calculateInitialStock([
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ]),
    lowStockThreshold: 8,
    imports: [],
    sales: [],
    isHidden: false,
  },
  {
    id: 76,
    name: "Giày nam Warrior 2025 phong cách trẻ trung",
    categoryId: "C001",
    price: 522500,
    oldPrice: 550000,
    img: "./img/casual_Warrior.png",
    rating: 4,
    ratingCount: 89,
    badge: "sale",
    description:
      "Giày Warrior 2025 với phong cách trẻ trung, giá cả hợp lý, chất liệu nhẹ và bền, phù hợp cho sinh viên và giới trẻ năng động.",
    images: ["./img/casual_Warrior.png", "./img/casual_Warrior.png"],
    variants: [
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ],
    costPrice: 370000,
    initialStock: calculateInitialStock([
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ]),
    lowStockThreshold: 8,
    imports: [],
    sales: [],
    isHidden: false,
  },
  {
    id: 77,
    name: "Giày nam Warrior 2025 phong cách trẻ trung",
    categoryId: "C001",
    price: 522500,
    oldPrice: 550000,
    img: "./img/casual_Warrior.png",
    rating: 4,
    ratingCount: 89,
    badge: "sale",
    description:
      "Giày Warrior 2025 với phong cách trẻ trung, giá cả hợp lý, chất liệu nhẹ và bền, phù hợp cho sinh viên và giới trẻ năng động.",
    images: ["./img/casual_Warrior.png", "./img/casual_Warrior.png"],
    variants: [
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ],
    costPrice: 370000,
    initialStock: calculateInitialStock([
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ]),
    lowStockThreshold: 8,
    imports: [],
    sales: [],
    isHidden: false,
  },
  {
    id: 78,
    name: "Giày nam Warrior 2025 phong cách trẻ trung",
    categoryId: "C001",
    price: 522500,
    oldPrice: 550000,
    img: "./img/casual_Warrior.png",
    rating: 4,
    ratingCount: 89,
    badge: "sale",
    description:
      "Giày Warrior 2025 với phong cách trẻ trung, giá cả hợp lý, chất liệu nhẹ và bền, phù hợp cho sinh viên và giới trẻ năng động.",
    images: ["./img/casual_Warrior.png", "./img/casual_Warrior.png"],
    variants: [
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ],
    costPrice: 370000,
    initialStock: calculateInitialStock([
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ]),
    lowStockThreshold: 8,
    imports: [],
    sales: [],
    isHidden: false,
  },
  {
    id: 79,
    name: "Giày nam Warrior 2025 phong cách trẻ trung",
    categoryId: "C001",
    price: 522500,
    oldPrice: 550000,
    img: "./img/casual_Warrior.png",
    rating: 4,
    ratingCount: 89,
    badge: "sale",
    description:
      "Giày Warrior 2025 với phong cách trẻ trung, giá cả hợp lý, chất liệu nhẹ và bền, phù hợp cho sinh viên và giới trẻ năng động.",
    images: ["./img/casual_Warrior.png", "./img/casual_Warrior.png"],
    variants: [
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ],
    costPrice: 370000,
    initialStock: calculateInitialStock([
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ]),
    lowStockThreshold: 8,
    imports: [],
    sales: [],
    isHidden: false,
  },
  {
    id: 80,
    name: "Giày nam Warrior 2025 phong cách trẻ trung",
    categoryId: "C001",
    price: 522500,
    oldPrice: 550000,
    img: "./img/casual_Warrior.png",
    rating: 4,
    ratingCount: 89,
    badge: "sale",
    description:
      "Giày Warrior 2025 với phong cách trẻ trung, giá cả hợp lý, chất liệu nhẹ và bền, phù hợp cho sinh viên và giới trẻ năng động.",
    images: ["./img/casual_Warrior.png", "./img/casual_Warrior.png"],
    variants: [
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ],
    costPrice: 370000,
    initialStock: calculateInitialStock([
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ]),
    lowStockThreshold: 8,
    imports: [],
    sales: [],
    isHidden: false,
  },
  {
    id: 81,
    name: "Giày nam Warrior 2025 phong cách trẻ trung",
    categoryId: "C001",
    price: 522500,
    oldPrice: 550000,
    img: "./img/casual_Warrior.png",
    rating: 4,
    ratingCount: 89,
    badge: "sale",
    description:
      "Giày Warrior 2025 với phong cách trẻ trung, giá cả hợp lý, chất liệu nhẹ và bền, phù hợp cho sinh viên và giới trẻ năng động.",
    images: ["./img/casual_Warrior.png", "./img/casual_Warrior.png"],
    variants: [
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ],
    costPrice: 370000,
    initialStock: calculateInitialStock([
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ]),
    lowStockThreshold: 8,
    imports: [],
    sales: [],
    isHidden: false,
  },
  {
    id: 82,
    name: "Giày nam Warrior 2025 phong cách trẻ trung",
    categoryId: "C001",
    price: 522500,
    oldPrice: 550000,
    img: "./img/casual_Warrior.png",
    rating: 4,
    ratingCount: 89,
    badge: "sale",
    description:
      "Giày Warrior 2025 với phong cách trẻ trung, giá cả hợp lý, chất liệu nhẹ và bền, phù hợp cho sinh viên và giới trẻ năng động.",
    images: ["./img/casual_Warrior.png", "./img/casual_Warrior.png"],
    variants: [
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ],
    costPrice: 370000,
    initialStock: calculateInitialStock([
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ]),
    lowStockThreshold: 8,
    imports: [],
    sales: [],
    isHidden: false,
  },
  {
    id: 83,
    name: "Giày nam Warrior 2025 phong cách trẻ trung",
    categoryId: "C001",
    price: 522500,
    oldPrice: 550000,
    img: "./img/casual_Warrior.png",
    rating: 4,
    ratingCount: 89,
    badge: "sale",
    description:
      "Giày Warrior 2025 với phong cách trẻ trung, giá cả hợp lý, chất liệu nhẹ và bền, phù hợp cho sinh viên và giới trẻ năng động.",
    images: ["./img/casual_Warrior.png", "./img/casual_Warrior.png"],
    variants: [
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ],
    costPrice: 370000,
    initialStock: calculateInitialStock([
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ]),
    lowStockThreshold: 8,
    imports: [],
    sales: [],
    isHidden: false,
  },
  {
    id: 84,
    name: "Giày nam Warrior 2025 phong cách trẻ trung",
    categoryId: "C001",
    price: 522500,
    oldPrice: 550000,
    img: "./img/casual_Warrior.png",
    rating: 4,
    ratingCount: 89,
    badge: "sale",
    description:
      "Giày Warrior 2025 với phong cách trẻ trung, giá cả hợp lý, chất liệu nhẹ và bền, phù hợp cho sinh viên và giới trẻ năng động.",
    images: ["./img/casual_Warrior.png", "./img/casual_Warrior.png"],
    variants: [
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ],
    costPrice: 370000,
    initialStock: calculateInitialStock([
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ]),
    lowStockThreshold: 8,
    imports: [],
    sales: [],
    isHidden: false,
  },
  {
    id: 85,
    name: "Giày nam Warrior 2025 phong cách trẻ trung",
    categoryId: "C001",
    price: 522500,
    oldPrice: 550000,
    img: "./img/casual_Warrior.png",
    rating: 4,
    ratingCount: 89,
    badge: "sale",
    description:
      "Giày Warrior 2025 với phong cách trẻ trung, giá cả hợp lý, chất liệu nhẹ và bền, phù hợp cho sinh viên và giới trẻ năng động.",
    images: ["./img/casual_Warrior.png", "./img/casual_Warrior.png"],
    variants: [
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ],
    costPrice: 370000,
    initialStock: calculateInitialStock([
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ]),
    lowStockThreshold: 8,
    imports: [],
    sales: [],
    isHidden: false,
  },
  {
    id: 86,
    name: "Giày nam Warrior 2025 phong cách trẻ trung",
    categoryId: "C001",
    price: 522500,
    oldPrice: 550000,
    img: "./img/casual_Warrior.png",
    rating: 4,
    ratingCount: 89,
    badge: "sale",
    description:
      "Giày Warrior 2025 với phong cách trẻ trung, giá cả hợp lý, chất liệu nhẹ và bền, phù hợp cho sinh viên và giới trẻ năng động.",
    images: ["./img/casual_Warrior.png", "./img/casual_Warrior.png"],
    variants: [
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ],
    costPrice: 370000,
    initialStock: calculateInitialStock([
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ]),
    lowStockThreshold: 8,
    imports: [],
    sales: [],
    isHidden: false,
  },
  {
    id: 87,
    name: "Giày nam Warrior 2025 phong cách trẻ trung",
    categoryId: "C001",
    price: 522500,
    oldPrice: 550000,
    img: "./img/casual_Warrior.png",
    rating: 4,
    ratingCount: 89,
    badge: "sale",
    description:
      "Giày Warrior 2025 với phong cách trẻ trung, giá cả hợp lý, chất liệu nhẹ và bền, phù hợp cho sinh viên và giới trẻ năng động.",
    images: ["./img/casual_Warrior.png", "./img/casual_Warrior.png"],
    variants: [
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ],
    costPrice: 370000,
    initialStock: calculateInitialStock([
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ]),
    lowStockThreshold: 8,
    imports: [],
    sales: [],
    isHidden: false,
  },
  {
    id: 88,
    name: "Giày nam Warrior 2025 phong cách trẻ trung",
    categoryId: "C001",
    price: 522500,
    oldPrice: 550000,
    img: "./img/casual_Warrior.png",
    rating: 4,
    ratingCount: 89,
    badge: "sale",
    description:
      "Giày Warrior 2025 với phong cách trẻ trung, giá cả hợp lý, chất liệu nhẹ và bền, phù hợp cho sinh viên và giới trẻ năng động.",
    images: ["./img/casual_Warrior.png", "./img/casual_Warrior.png"],
    variants: [
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ],
    costPrice: 370000,
    initialStock: calculateInitialStock([
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ]),
    lowStockThreshold: 8,
    imports: [],
    sales: [],
    isHidden: false,
  },
  {
    id: 89,
    name: "Giày nam Warrior 2025 phong cách trẻ trung",
    categoryId: "C001",
    price: 522500,
    oldPrice: 550000,
    img: "./img/casual_Warrior.png",
    rating: 4,
    ratingCount: 89,
    badge: "sale",
    description:
      "Giày Warrior 2025 với phong cách trẻ trung, giá cả hợp lý, chất liệu nhẹ và bền, phù hợp cho sinh viên và giới trẻ năng động.",
    images: ["./img/casual_Warrior.png", "./img/casual_Warrior.png"],
    variants: [
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ],
    costPrice: 370000,
    initialStock: calculateInitialStock([
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ]),
    lowStockThreshold: 8,
    imports: [],
    sales: [],
    isHidden: false,
  },
  {
    id: 90,
    name: "Giày nam Warrior 2025 phong cách trẻ trung",
    categoryId: "C001",
    price: 522500,
    oldPrice: 550000,
    img: "./img/casual_Warrior.png",
    rating: 4,
    ratingCount: 89,
    badge: "sale",
    description:
      "Giày Warrior 2025 với phong cách trẻ trung, giá cả hợp lý, chất liệu nhẹ và bền, phù hợp cho sinh viên và giới trẻ năng động.",
    images: ["./img/casual_Warrior.png", "./img/casual_Warrior.png"],
    variants: [
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ],
    costPrice: 370000,
    initialStock: calculateInitialStock([
      { size: 39, stock: 20 },
      { size: 40, stock: 25 },
      { size: 41, stock: 22 },
      { size: 42, stock: 18 },
      { size: 43, stock: 12 },
    ]),
    lowStockThreshold: 8,
    imports: [],
    sales: [],
    isHidden: false,
  },
];
